"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ActionEnum;
(function (ActionEnum) {
    ActionEnum[ActionEnum["UNKNOWN"] = 0] = "UNKNOWN";
    ActionEnum[ActionEnum["BOARD_ADD"] = 1] = "BOARD_ADD";
    ActionEnum[ActionEnum["BOARD_GET_BY_HASH"] = 2] = "BOARD_GET_BY_HASH";
    ActionEnum[ActionEnum["BOARD_GET"] = 3] = "BOARD_GET";
    ActionEnum[ActionEnum["BOARD_DELETE"] = 4] = "BOARD_DELETE";
    ActionEnum[ActionEnum["BOARD_GET_CONFIGURATION"] = 5] = "BOARD_GET_CONFIGURATION";
    ActionEnum[ActionEnum["BOARDS_LIST"] = 6] = "BOARDS_LIST";
    ActionEnum[ActionEnum["STORY_DELETE"] = 7] = "STORY_DELETE";
    ActionEnum[ActionEnum["STORY_ADD_TO_BOARD"] = 8] = "STORY_ADD_TO_BOARD";
    ActionEnum[ActionEnum["STORY_UPDATE"] = 9] = "STORY_UPDATE";
    ActionEnum[ActionEnum["TASK_MOVE"] = 10] = "TASK_MOVE";
    ActionEnum[ActionEnum["TASK_GET"] = 11] = "TASK_GET";
    ActionEnum[ActionEnum["TASK_DELETE"] = 12] = "TASK_DELETE";
    ActionEnum[ActionEnum["TASK_ADD_TO_STORY"] = 13] = "TASK_ADD_TO_STORY";
    ActionEnum[ActionEnum["TASK_UPDATE_TEXT"] = 14] = "TASK_UPDATE_TEXT";
    ActionEnum[ActionEnum["STORY_GET"] = 15] = "STORY_GET";
    ActionEnum[ActionEnum["STORY_UPDATE_TEXT"] = 16] = "STORY_UPDATE_TEXT";
    ActionEnum[ActionEnum["BOARD_SET_CONFIGURATION"] = 17] = "BOARD_SET_CONFIGURATION";
    ActionEnum[ActionEnum["BOARD_SORT_STORY"] = 18] = "BOARD_SORT_STORY";
    ActionEnum[ActionEnum["TASK_UPDATE_STATUS"] = 19] = "TASK_UPDATE_STATUS";
    ActionEnum[ActionEnum["USER_SIGN_IN_TRY"] = 20] = "USER_SIGN_IN_TRY";
    ActionEnum[ActionEnum["USER_ADD"] = 21] = "USER_ADD";
    ActionEnum[ActionEnum["USER_ADD_SHARED_BOARD"] = 22] = "USER_ADD_SHARED_BOARD";
    ActionEnum[ActionEnum["USER_GET"] = 23] = "USER_GET";
    ActionEnum[ActionEnum["USER_UPDATE"] = 24] = "USER_UPDATE";
    ActionEnum[ActionEnum["BOARD_GET_ARCHIVE"] = 25] = "BOARD_GET_ARCHIVE";
    ActionEnum[ActionEnum["BOARD_SET_STATUS"] = 26] = "BOARD_SET_STATUS";
    ActionEnum[ActionEnum["STORY_SET_STATUS"] = 27] = "STORY_SET_STATUS";
    ActionEnum[ActionEnum["USER_GET_RECENT_TASKS"] = 28] = "USER_GET_RECENT_TASKS";
    ActionEnum[ActionEnum["NOTE"] = 29] = "NOTE";
})(ActionEnum = exports.ActionEnum || (exports.ActionEnum = {}));
